# Generated by Django 6.0.4 on 2026-04-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ex02", "0003_alter_tip_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tip",
            options={},
        ),
    ]
