# Generated by Django 6.0.4 on 2026-04-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ex02", "0002_tip_downvoters_tip_upvoters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tip",
            options={"permissions": [("can_downvote_tip", "Can downvote tip")]},
        ),
    ]
